repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^test outputs/
      - id: mixed-line-ending
        exclude: ^test outputs/
        args:
          - --fix=lf
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.0
    hooks:
    - id: clang-format
      exclude: ^test inputs/
